Development
glazkov-vv/PythonProject pull request #2
Opened 2024-05-06 15:58 UTC by glazkov-vv

2024-05-07 21:06 UTC, dKosarevsky commented on __pycache__/AAA.cpython-310.pyc
этому не место в репо

2024-05-07 21:09 UTC, dKosarevsky requested changes
в проекте следует "прибраться" в части PEP8

2024-05-07 21:09 UTC, dKosarevsky commented on app.py
> +# def build_list(fileEntries:iterable[file]) -> urwid.Filler:
зачем? следует убрать

2024-05-07 21:09 UTC, dKosarevsky commented on cli/error.py
> +    def __init__(self, value) -> None:
typehint

2024-05-07 21:09 UTC, dKosarevsky commented on cli/executestransactions.py
> +    async def execute_transaction(self,transaction:Transaction,is_cancellation=False)->None:
PEP8

2024-05-07 21:09 UTC, dKosarevsky commented on cli/filepanel.py
> +        #lbx=urwid.ListBox([PanelPath(self._custom_data)]+[TitleEntry(self._custom_data)]+[urwid.BoxAdapter(urwid.ListBox([FileEntry(self._custom_data,h,self.pos,workspace) for h in workspace.get_con
зачем?

2024-05-07 21:09 UTC, dKosarevsky commented on cli/filepanel.py
> +    def __init__(self,custom_data,workspace:Workspace,pos:int=0) -> None:
PEP8

2024-05-07 21:09 UTC, dKosarevsky commented on cli/filepanel.py
> +            #self.body.focus_position=1
?

2024-05-07 21:09 UTC, dKosarevsky commented on cli/filepanel.py
> +            #cols=titleentry.contents[0][0]
?

2024-05-07 21:09 UTC, dKosarevsky commented on cli/filepanel.py
> +        #self.body.set_focus_path(oldpath)
?

2024-05-07 21:09 UTC, dKosarevsky commented on cli/filepanel.py
> +
??

2024-05-07 22:11 UTC, merged

2024-05-08 20:44 UTC, dKosarevsky commented
а зачем вмёржил?

2024-05-08 20:46 UTC, glazkov-vv commented
Так написал же в телеграме - вмерджил сдуру.

2024-05-08 20:46 UTC, glazkov-vv commented
Открыл новый request